### ISSUE TITLE
OutOfMemoryError when playing hard level game

### ISSUE THREAD

**Issue by sirekanyan** [SecUSo/privacy-friendly-memo-game#5]
Samsung Galaxy Note II GT-N7100
Android 4.4.4 / CyanogenMod-11-20160815-NIGHTLY-n7100
```
12-03 12:31:28.480 E/dalvikvm-heap( 4281): Out of memory on a 1048592-byte allocation.
12-03 12:31:28.485 I/dalvikvm( 4281): "main" prio=5 tid=1 RUNNABLE
12-03 12:31:28.485 I/dalvikvm( 4281):   | group="main" sCount=0 dsCount=0 obj=0x41721de0 self=0x400514d0
12-03 12:31:28.485 I/dalvikvm( 4281):   | sysTid=4281 nice=0 sched=0/0 cgrp=apps handle=1074475348
12-03 12:31:28.485 I/dalvikvm( 4281):   | state=R schedstat=( 87520701562 13296658371 115844 ) utm=7669 stm=1082 core=3
12-03 12:31:28.485 I/dalvikvm( 4281):   at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
12-03 12:31:28.500 I/dalvikvm( 4281):   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
12-03 12:31:28.500 I/dalvikvm( 4281):   at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
12-03 12:31:28.500 I/dalvikvm( 4281):   at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
12-03 12:31:28.505 I/dalvikvm( 4281):   at android.content.res.Resources.loadDrawable(Resources.java:2249)
12-03 12:31:28.505 I/dalvikvm( 4281):   at android.content.res.Resources.getDrawable(Resources.java:733)
12-03 12:31:28.505 I/dalvikvm( 4281):   at android.content.res.Resources.getDrawable(Resources.java:711)
12-03 12:31:28.505 I/dalvikvm( 4281):   at android.widget.ImageView.resolveUri(ImageView.java:636)
12-03 12:31:28.505 I/dalvikvm( 4281):   at android.widget.ImageView.setImageResource(ImageView.java:366)
12-03 12:31:28.515 I/dalvikvm( 4281):   at org.secuso.privacyfriendlymemory.ui.MemoImageAdapter.getView(MemoImageAdapter.java:79)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.AbsListView.obtainView(AbsListView.java:2255)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.GridView.makeAndAddView(GridView.java:1345)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.GridView.makeRow(GridView.java:345)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.GridView.fillDown(GridView.java:287)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.GridView.fillSpecific(GridView.java:566)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.GridView.layoutChildren(GridView.java:1244)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.AbsListView.onLayout(AbsListView.java:2087)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1367)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:849)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.View.layout(View.java:14841)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.515 I/dalvikvm( 4281):   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1986)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1743)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.view.Choreographer.doFrame(Choreographer.java:544)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.os.Handler.handleCallback(Handler.java:733)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.os.Handler.dispatchMessage(Handler.java:95)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.os.Looper.loop(Looper.java:136)
12-03 12:31:28.520 I/dalvikvm( 4281):   at android.app.ActivityThread.main(ActivityThread.java:5146)
12-03 12:31:28.520 I/dalvikvm( 4281):   at java.lang.reflect.Method.invokeNative(Native Method)
12-03 12:31:28.530 I/dalvikvm( 4281):   at java.lang.reflect.Method.invoke(Method.java:515)
12-03 12:31:28.530 I/dalvikvm( 4281):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
12-03 12:31:28.535 I/dalvikvm( 4281):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
12-03 12:31:28.535 I/dalvikvm( 4281):   at dalvik.system.NativeStart.main(Native Method)
12-03 12:31:28.535 I/dalvikvm( 4281): 
12-03 12:31:28.535 D/skia    ( 4281): --- allocation failed for scaled bitmap
12-03 12:31:28.550 D/AndroidRuntime( 4281): Shutting down VM
12-03 12:31:28.550 W/dalvikvm( 4281): threadid=1: thread exiting with uncaught exception (group=0x41720ce0)
12-03 12:31:28.575 E/AndroidRuntime( 4281): FATAL EXCEPTION: main
12-03 12:31:28.575 E/AndroidRuntime( 4281): Process: org.secuso.privacyfriendlymemory, PID: 4281
12-03 12:31:28.575 E/AndroidRuntime( 4281): java.lang.OutOfMemoryError
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.content.res.Resources.loadDrawable(Resources.java:2249)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.content.res.Resources.getDrawable(Resources.java:733)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.content.res.Resources.getDrawable(Resources.java:711)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.ImageView.resolveUri(ImageView.java:636)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.ImageView.setImageResource(ImageView.java:366)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at org.secuso.privacyfriendlymemory.ui.MemoImageAdapter.getView(MemoImageAdapter.java:79)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.AbsListView.obtainView(AbsListView.java:2255)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.GridView.makeAndAddView(GridView.java:1345)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.GridView.makeRow(GridView.java:345)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.GridView.fillDown(GridView.java:287)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.GridView.fillSpecific(GridView.java:566)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.GridView.layoutChildren(GridView.java:1244)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.AbsListView.onLayout(AbsListView.java:2087)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1367)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:849)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.View.layout(View.java:14841)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1986)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1743)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
12-03 12:31:28.575 E/AndroidRuntime( 4281): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreog
12-03 12:31:28.640 W/ActivityManager( 2299):   Force finishing activity org.secuso.privacyfriendlymemory/.ui.MemoActivity
12-03 12:31:29.145 W/ActivityManager( 2299): Activity pause timeout for ActivityRecord{41cf7300 u0 org.secuso.privacyfriendlymemory/.ui.MemoActivity t7 f}
12-03 12:31:30.390 I/Process ( 4281): Sending signal. PID: 4281 SIG: 9
12-03 12:31:30.515 I/ActivityManager( 2299): Process org.secuso.privacyfriendlymemory (pid 4281) has died.
```

**Comment by Yonjuni** [comment]
Thanks for the stack trace.
Could you tell me how far you could play the game and when exactly it happened?

**Comment by Xrygramming** [comment]
Hi,

thanks for the information. The stack trace shows that the issue occurs when a default card deck is selected.

Does the exception occurs for both default card decks and is it thrown everytime or just once? Could not reproduce it locally.

**Comment by sirekanyan** [comment]
Hi, the error happens for both default card themes.

It is reproduced quite often on my phone. Approximately when I playing for about 10 or 20 minutes. Easy level game may crash too.

The most repeated case for me is:
1) play 5-10 minutes on hard/medium/easy game
2) open 'about' page from navigation drawer
3) app immediately crashes with oom ('about' page didn't appear). Stacktrace is similar to one i've posted. I'll post it a little bit later.

It seems that problem is specific for galaxy note II with cyanogenmod. It never happens on nexus device with stock firmware.

**Comment by Yonjuni** [comment]
@sirekanyan Is it playing one single game for 5-10 minutes or multiple ones?

**Comment by Yonjuni** [comment]
@sirekanyan Could you test if it is still happening with this beta version? I have added a quick fix idea to it, but as I cannot reproduce the issue, I also cannot test whether it is working :)
[PF-Memo-Game_v1.0.2_beta.apk.zip](https://github.com/SecUSo/privacy-friendly-memo-game/files/671429/PF-Memo-Game_v1.0.2_beta.apk.zip)

**Comment by Yonjuni** [comment]
It is not only in the hard level, it occurs at the very end of a game while many cards are open.

**Comment by Yonjuni** [comment]
Should be fine in version 1.0.2
